#!/bin/bash
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd)
RUNNER_SCRIPT=${0##*/}

RUNNER_BASE_DIR=${RUNNER_SCRIPT_DIR%/*}
RUNNER_ETC_DIR=$RUNNER_BASE_DIR/etc
RUNNER_LOG_DIR={{log_path}}
RUNNER_USER={{run_user}}

# Make sure this script is running as the appropriate user
if [ ! -z "$RUNNER_USER" ] && [ `whoami` != "$RUNNER_USER" ]; then
    exec sudo -u $RUNNER_USER $0 $@
fi

# Make sure CWD is set to runner base dir
cd $RUNNER_BASE_DIR

# Extract the target node name and cookie from vm.args
if [ ! -f "$RUNNER_ETC_DIR/vm.args" ]; then
    NODENAME=`egrep '^[ \t]*nodename[ \t]*=[ \t]*' $RUNNER_ETC_DIR/{{cuttlefish_conf}} 2> /dev/null | tail -n 1 | cut -d = -f 2`
    if [ -z "$NODENAME" ]; then
        echo "vm.args needs to have a -name parameter."
        echo "  -sname is not supported."
        exit 1
    else
        NAME_ARG="-name ${NODENAME# *}"
    fi
    COOKIE=`egrep '^[ \t]*distributed_cookie[ \t]*=[ \t]*' $RUNNER_ETC_DIR/{{cuttlefish_conf}} 2> /dev/null | cut -d = -f 2`
    if [ -z "$COOKIE" ]; then
        echo "vm.args needs to have a -setcookie parameter."
        exit 1
    else
        COOKIE_ARG="-setcookie $COOKIE"
    fi
else
    NAME_ARG=`egrep '^\-name' $RUNNER_ETC_DIR/vm.args 2> /dev/null`
    if [ -z "$NAME_ARG" ]; then
        echo "vm.args needs to have a -name parameter."
        echo "  -sname is not supported."
        exit 1
    fi
    COOKIE_ARG=`grep -e '-setcookie' $RUNNER_ETC_DIR/vm.args 2> /dev/null`
    if [ -z "$COOKIE" ]; then
        echo "vm.args needs to have a -setcookie parameter."
        exit 1
    fi
fi

# Learn how to specify node name for connection from remote nodes
echo "$NAME_ARG" | grep '^-sname' > /dev/null 2>&1
if [ "X$?" = "X0" ]; then
    NAME_PARAM="-sname"
    NAME_HOST=""
else
    NAME_PARAM="-name"
    echo "$NAME_ARG" | grep '@.*' > /dev/null 2>&1
    if [ "X$?" = "X0" ]; then
        NAME_HOST=`echo "${NAME_ARG}" | sed -e 's/.*\(@.*\)$/\1/'`
    else
        NAME_HOST=""
    fi
fi

# Identify the script name
SCRIPT=`basename $0`

# Parse out release and erts info
START_ERL=`cat $RUNNER_BASE_DIR/releases/start_erl.data`
ERTS_VSN=${START_ERL% *}
APP_VSN=${START_ERL#* }

# Add ERTS bin dir to our path
ERTS_PATH=$RUNNER_BASE_DIR/erts-$ERTS_VSN/bin

# Setup command to control the node
NODETOOL="$ERTS_PATH/escript $ERTS_PATH/nodetool $NAME_ARG $COOKIE_ARG"

run()
{

    TIMEOUT=""
    if [ "$1" == "-t" ]
    then
        TIMEOUT="-t $2"
        shift
        shift
    fi

    mod=$1
    shift
    cmd=$1
    shift

    # Make sure the local node IS running
    RES=`$NODETOOL ping`
    if [ "$RES" != "pong" ]; then
        echo "Node is not running!"
        exit 1
    fi

    $NODETOOL $TIMEOUT rpc $mod $cmd $@
}
# Check the first argument for instructions
case "$1" in
    users)
        shift
        case "$1" in
            list)
                shift
                run snarl_console list_user $@
                ;;
            add)
                shift
                run snarl_console add_user $@
                ;;
            join)
                shift
                run snarl_console join_role $@
                ;;
            leave)
                shift
                run snarl_console leave_role $@
                ;;
            passwd)
                shift
                run snarl_console passwd $@
                ;;
            grant)
                shift
                run snarl_console grant_user $@
                ;;
            revoke)
                shift
                run snarl_console revoke_user $@
                ;;
            "delete")
                shift
                run snarl_console delete_user $@
                ;;
            "export")
                shift
                run snarl_console export_user $@
                ;;
            "import")
                shift
                run snarl_console import_user $@
                ;;
            *)
                echo "Usage: snarl-admin users { add | passwd | join | leave "
                echo "                           grant | revoke }."
                exit 1
                ;;
        esac
        ;;
    roles)
        shift
        case "$1" in
            list)
                shift
                run snarl_console list_role $@
                ;;
            add)
                shift
                run snarl_console add_role $@
                ;;
            grant)
                shift
                run snarl_console grant_role $@
                ;;
            revoke)
                shift
                run snarl_console revoke_role $@
                ;;
            "delete")
                shift
                run snarl_console delete_role $@
                ;;
            "export")
                shift
                run snarl_console export_role $@
                ;;
            "import")
                shift
                run snarl_console import_role $@
                ;;
            *)
                echo "Usage: snarl-admin roles { list | add | grant | revoke }."
                exit 1
                ;;
        esac
        ;;


    join)
        shift
        run snarl_console join $@
        ;;

    leave)
        shift
        run snarl_console leave $@
        ;;

    remove)
        if [ $# -ne 2 ]; then
            echo "Usage: $SCRIPT remove <node>"
            exit 1
        fi

        shift
        run snarl_console remove $@
        ;;

    reip)
        shift
        run snarl_console reip $@
        ;;

    aae-status|aae_status)
        shift
        run snarl_console aae_status $@
        ;;

    member-status|member_status)
        if [ $# -ne 1 ]; then
            echo "Usage: $SCRIPT member_status"
            exit 1
        fi

        shift
        run riak_core_console member_status $@
        ;;

    ring-status|ring_status)
        if [ $# -ne 1 ]; then
            echo "Usage: $SCRIPT ring_status"
            exit 1
        fi

        shift
        run riak_core_console ring_status $@
        ;;

    services)
        $NODETOOL rpcterms riak_core_node_watcher services ''
        ;;

    wait-for-service)
        SVC=$2
        TARGETNODE=$3
        if [ $# -lt 3 ]; then
            echo "Usage: $SCRIPT wait-for-service <service_name> <target_node>"
            exit 1
        fi

        while (true); do
            # Make sure riak_core_node_watcher is up and running locally before trying to query it
            # to avoid ugly (but harmless) error messages
            NODEWATCHER=`$NODETOOL rpcterms erlang whereis "'riak_core_node_watcher'."`
            if [ "$NODEWATCHER" = "undefined" ]; then
                echo "$SVC is not up: node watcher is not running"
                continue
            fi

            # Get the list of services that are available on the requested node
            SERVICES=`$NODETOOL rpcterms riak_core_node_watcher services "'${TARGETNODE}'."`
            echo "$SERVICES" | grep "[[,]$SVC[],]" > /dev/null 2>&1
            if [ "X$?" = "X0" ]; then
                echo "$SVC is up"
                exit 0
            else
                echo "$SVC is not up: $SERVICES"
            fi
            sleep 3
        done
        ;;

    ringready)
        shift
        run snarl_console ringready $@
        ;;
    config)
        shift
        run snarl_console config $@
        ;;
    status)
        shift
        run snarl_console status $@
        ;;
    ring)
        run snarl_console get_ring
        ;;
    db)
        shift
        case "$1" in
            list)
                shift
                run snarl_console db_keys $@
                ;;
            get)
                shift
                run snarl_console db_get $@
                ;;
            delete)
                shift
                run snarl_console db_delete $@
                ;;
            update)
                shift
                run -t infinity snarl_console db_update $@
                ;;
        esac
        ;;
    scope)
        shift
        case "$1" in
            list)
                shift
                run snarl_console scope_list $@
                ;;
            add)
                shift
                run snarl_console scope_add $@
                ;;
            delete)
                shift
                run snarl_console scope_del $@
                ;;
            grant)
                shift
                run snarl_console scope_grant $@
                ;;
            revoke)
                shift
                run snarl_console scope_revoke $@
                ;;

        esac
        ;;
    init)
        run snarl_console init_user $@
        ;;

    *)
        echo "Usage: $SCRIPT { join | leave | reip | ringready | remove |"
        echo "                 services | wait-for-service | member_status |"
        echo "                 ring_status | status}"
        echo "               ring                                       - shows the ring."
        echo "               db update [<section>]                      - lists db entries."
        echo "               db list [-p <prefix>]                      - lists db entries."
        echo "               db list <hash> [<prefix>]                  - lists db entries for a hash."
        echo "               db get <hash> <prefix> <key>               - gets raw data from the db."
        echo "               db delete <hash> <prefix> <key>            - deletes directly from db."
        echo "               config show                                - shows global config options."
        echo "               config set <key> <value>                   - sets global config options."
        echo "               users list <realm>                         - list users."
        echo "               users add <realm> <user>                   - adds a new user."
        echo "               users delete <realm> <uuid>                - deletes a user."
        echo "               users passwd <realm> <user> <passwd>       - sets user password."
        echo "               users grant <realm> <user> <permission>    - grants a permission."
        echo "               users revoke <realm> <user> <permission>   - revokes a permission"
        echo "               users join <realm> <user> <role>           - adds user to a role."
        echo "               users leave <realm> <user> <role>          - removes user from a role."
        echo "               users export <realm> <uuid>                - Exports a user to a json file."
        echo "               users import <realm> <file>                - imports a user json file."
        echo "               roles add <realm> <role>                   - adds a role."
        echo "               roles delete <realm> <uuid>                - deletes a role."
        echo "               roles grant <realm> <role> <permission>    - grants a permission."
        echo "               roles revoke <realm> <role> <permission>   - revokes a permission."
        echo "               roles export <realm> <uuid>                - Exports a role to a json file."
        echo "               role import <realm> <file>                 - imports a role json file."
        echo "               intit <realm> <org> <user> <pass>          - initializes a realm with a fresh org and user."
        exit 1
        ;;
esac
